name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: staging
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Generate build number
      run: echo "The build number $GITHUB_RUN_NUMBER ğŸ—"
    - name: Install dependencies
      run: | 
        npm install
    - name: Create .env
      run: |
        touch .env &&
        echo "DEBUG=${DEBUG}" > .env
        echo "LOG_LEVEL=${LOG_LEVEL}" >> .env
        echo "ENVIRONMENT=${ENVIRONMENT}" >> .env
        echo "NODE_ENV=${NODE_ENV}" >> .env
        echo "PORT=${PORT}" >> .env
        echo "METRICS_PREFIX=${METRICS_PREFIX}" >> .env
        echo "NAME=${NAME}" >> .env
      env:
        DEBUG: ${{ secrets.DEBUG }}
        LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
        ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        NODE_ENV: ${{ secrets.NODE_ENV }}
        PORT: ${{ secrets.PORT }}
        METRICS_PREFIX: ${{ secrets.METRICS_PREFIX }}
        NAME: ${{ secrets.NAME }}
    - name: Run test ğŸ§ª
      run: | 
        npm run test:ci
    - name: Run eslint ğŸ§¹ğŸ§
      run: | 
        npm run eslint
    - name: Build docker ğŸ³
      run: docker build . -t=hexa-shopping-cart-orders-api:ghb-$GITHUB_RUN_NUMBER